### ISSUE TITLE
Is log-cache really optional?

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry/cf-deployment#622] opened 2018-09-19 13:20 UTC
Hello,
we have successfully upgraded CF from 2.6.0 to 3.6.0 using the "disable-log-cache" component due to #586 .

Now we are testing the update from 3.6.0 to 4.4.0 and we were not able to successfully deploy CF due to https://github.com/cloudfoundry/capi-release/issues/105.
So we tried by using capi-release v1.66.0 with CF v4.4.0 and the deployment was successful but:
- our monitor cf test failed with:
```
018-09-19T11:39:05.64+0000 [Loggregator/] ERR recent log endpoint requires a log cache. please talk to you operator
```
- all the apps are reporiting 0% cpu usage and 0.0MB ram usage. So I guess the apps' logs do not reach the proper endpoint.

As soon as we enabled log-cache (by removing the disable-log-cache ops file), everything ran fine and all tests became green again.

The problem is that due to #586 we can't enable it on our productive landscapes.

**Comment by heyjcollins** [comment] 2018-09-19 21:58
Hi @paolostivanin -
Thanks for bringing this to our attention. We do expect the `disable-log-cache.yml` ops file to work as intended. The CAPI team is investigating and hopefully we'll get a fix in to a future release ([see this slack conversation](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1537393595000100)) however I want to make it clear that we plan to deprecate this ops file in the near future - it was introduced as a failsafe initially in case log-cache was proving unstable for folks running CF configurations that weren't covered. We've received and responded to feedback from the field and are rounding the bend on that decision.

**Comment by heyjcollins** [comment] 2018-09-19 21:59
I'm going to close this issue given we're responding to it.
If you'd like to discuss further, feel free to reopen.

**Closed by heyjcollins** 2018-09-19 21:59 UTC
Labels: unscheduled

**Comment by heyjcollins** [comment] 2018-09-21 18:30
Just a quick followup on this @paolostivanin: 
We're going to deprecate disable-log-cache.yml and will be removing the file completely in cf-d 6.0 as Log-Cache release has been stable within our large scale environment (PWS) for several weeks now.
I'd say it's safe to run with it enabled in your CF, but if you experience otherwise, please reach out to the [log-cache team on Slack](https://cloudfoundry.slack.com/messages/CBFB7NP9B).
