### ISSUE TITLE
log-cache cert not valid for log-cache.service.cf.internal

### ISSUE THREAD

**Issue by dennisjbell** [cloudfoundry/cf-deployment#1113] opened 2023-08-18 06:13 UTC
### What is this issue about?

Though cf-deployment.yml references the log-cache through bosh-dns-alias log-cache.service.cf.internal multiple times, as well as declaring that bosh-dns-alias entry, the certificate generated by variables section only provides alternative names of logcache, log-cache, and log_cache (see https://github.com/cloudfoundry/cf-deployment/blob/main/cf-deployment.yml#L2281C2-L2284C15)

### What version of [cf-deployment](https://github.com/cloudfoundry/cf-deployment/releases) are you using?

Noticed in cf-deployment v29.0.0, still present in current HEAD

### Please provide output that helps describe the issue:

When deploying cf-app-autoscaler, the following errors were noted in the eventgenerator log:
<img width="1669" alt="image" src="https://github.com/cloudfoundry/cf-deployment/assets/20423/9e97766c-c17d-409d-9f21-c3b7e74a0735">

### What IaaS is this issue occurring on?

Not an IaaS issue, as it is in the general manifest. However, it is confirmed present on vSphere, AWS, Google, Azure in the exact same manner.

### Is there anything else unique or special about your setup?

We had to also add log-cache bosh-dns-release to the enable-log-cache operator file in cf-app-autoscaler. See https://github.com/cloudfoundry/app-autoscaler-release/issues/2071

### Tag your pair, your PM, and/or team!
Discovered and diagnosed by @wayneeseguin, @itsouvalas, @dennisjbell, @norman-abramovitz and @krutten

**Comment by chombium** [comment] 2023-08-21 09:26
The used certificate is wrong. I've written more details in the issue opened in the  application autoscaler repo mentioned above. We can close this ticket a duplicate of the one in the application autoscaler repo.

**Comment by dennisjbell** [comment] 2023-08-21 18:46
Can you link to the ticket in the autoscaler repo please?

**Closed** 2023-08-21 22:47 UTC
