### ISSUE TITLE
Anchors, instead of links, make IPs difficult to override.

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/cf-deployment#46] opened 2017-01-21 04:46 UTC
Hi there!

I'm trying to create an override file which will allow for a minimal, instead of HA deployment.

I'm including lines like these to slim down the static IPs specified:

```
- type: remove
  path: /instance_groups/name=consul/networks/name=private/static_ips/2
- type: remove
  path: /instance_groups/name=consul/networks/name=private/static_ips/1
- type: remove
  path: /instance_groups/name=nats/networks/name=private/static_ips/1
```

... unfortunately, the sets of two and three IPs continue to show up all throughout the manifest. That doesn't seem to affect deployment, but it's messy. Here's an example:

```
          servers:
            lan:
            - 10.0.31.190
            - 10.0.47.190
            - 10.0.63.190
```

A certain @cppforlife suggested that it's because you're using YAML anchors, instead of BOSH links.

**Comment by dsabeti** [comment] 2017-01-24 00:35
@menicosia Yep. The problem is that links are typically defined at the release level. In this case, consul-release would need to have its servers providing the link and its agents consuming the link. 

I did recently learn about manual links, which allows you to *provide* links without modifying the release, but as far as I know you can't use manual links to consume links. @cppforlife can correct me if I'm wrong. Until consul-release knows how to consume links, we need the static IPs. (Same goes for nats-release.) They have story do it soon: https://www.pivotaltracker.com/story/show/132721819.

FWIW, I think we can remove some of the non-consul static IPs. For example, we're currently using a static IP for mysql. But we could probably use a colocated a switchboard proxy, which uses consul urls instead of static IPs. I'll update this issue when I've written stories to address this.

**Comment by dsabeti** [comment] 2017-02-22 22:46
Hey @menicosia. If you don't object, I'd like to close the issue. We have movement on all of the static IPs:
- consul: now uses a link
- nats: moving towards links. Still have a [a few more stories](https://www.pivotaltracker.com/story/show/140423893).
- DB: using [consul/DNS](https://www.pivotaltracker.com/story/show/138346625)

**Closed** 2017-03-09 04:18 UTC
Labels: unscheduled
