### ISSUE TITLE
Stager is unavailable: getaddrinfo: Name or service not known (bbs.service.cf.internal:8889)

### ISSUE THREAD

**Issue by prashantgnet** [cloudfoundry/cf-deployment#425] opened 2018-03-05 09:22 UTC
Hello,

I am randomly getting following error message during application push 
Environment details:-
Openstack
cf-deployment v1.15.0
Default i.e. three zone deployment 
```
Staging app and tracing logs...
Unexpected Response
Response code: 503
CC code:       0
CC error code: 
Request ID:    985801b7-4ece-4a9f-50ed-9090a2137c91::c7461552-b6e6-49ce-bf68-f9a7c1b56626
Description:   {
  "description": "Stager is unavailable: getaddrinfo: Name or service not known (bbs.service.cf.internal:8889)",
  "error_code": "CF-StagerUnavailable",
  "code": 170010
``` 

I have seen following error message under diego-api instance for bbs job
```
bbs.stdout.log:{"timestamp":"1520238148.070505619","source":"bbs","message":"bbs.exited-with-failure","log_level":2,"data":{"error":"Exit trace for group:\nlock exited with error: Exit trace for group:\nsql-lock exited with error: sql-lock: failed to start in time\nlock-maintainer exited with nil\n\nlock-held-metrics exited with nil\nperiodic-filedescriptor-metrics exited with nil\ntask-stat-metron-notifier exited with nil\nhealthcheck exited with nil\ndebug-server exited with nil\n"}}

bbs.stdout.log:{"timestamp":"1520236955.683034658","source":"bbs","message":"bbs.locket-lock.failed-to-acquire-lock","log_level":2,"data":{"error":"rpc error: code = 6 desc = lock-collision","lock":{"key":"bbs","owner":"5caf52dd-1170-4ce8-b3ba-0dca6ca54888","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}

bbs.stdout.log:{"timestamp":"1520236955.683034658","source":"bbs","message":"bbs.locket-lock.failed-to-acquire-lock","log_level":2,"data":{"error":"rpc error: code = 6 desc = lock-collision","lock":{"key":"bbs","owner":"5caf52dd-1170-4ce8-b3ba-0dca6ca54888","type":"lock","type_code":1},"session":"5","ttl_in_seconds":15}}
```

Kindly let me know for specific log information or setup details. I will provide it.

Thanks,
Prashant

**Comment by dsabeti** [comment] 2018-03-05 16:37
Hey @prashantgnet. The error suggests that the BBS in your deployment is having issues connecting to its database. Which database are you using?

cc @emalm

**Comment by prashantgnet** [comment] 2018-03-05 17:05
Hello,

I am using default MySQL database. I will share the logs from database instance or let me know any specific log.

Thanks,
Prashant

On 05-Mar-2018 10:08 PM, David Sabeti <notifications@github.com> wrote:

EXTERNAL

Hey @prashantgnet<https://github.com/prashantgnet>. The error suggests that the BBS in your deployment is having issues connecting to its database. Which database are you using?

cc @emalm<https://github.com/emalm>

-

**Comment by jvshahid** [comment] 2018-03-05 17:27
@prashantgnet can you upload the `diego-api` job logs. i'm wondering if BBS is crashing and not releasing the lock properly.

**Comment by jvshahid** [comment] 2018-03-05 18:02
moved the tracker story to `CF Diego Public`

**Comment by prashantgnet** [comment] 2018-03-06 05:46
[bbs.stderr.log](https://github.com/cloudfoundry/cf-deployment/files/1783677/bbs.stderr.log)
[bbs.stdout1.log](https://github.com/cloudfoundry/cf-deployment/files/1783678/bbs.stdout1.log) 

Kindly check the attached log files from diego-api instance for bbs job. 

Thanks,
Prashant

**Comment by prashantgnet** [comment] 2018-03-06 08:36
[bbs.stdout.log](https://github.com/cloudfoundry/cf-deployment/files/1784121/bbs.stdout.log)

full log of bbs

**Comment by charlievieth** [comment] 2018-03-06 21:07
@prashantgnet It looks like the root of this issue may lie with MySQL, could you send us the My logs from the `database` instance(s) in you deployment?  You should be able to get them with something like: `bosh -d cf logs database`.

**Comment by jvshahid** [comment] 2018-03-06 21:50
@charlievieth it looks like the bbs is restarting. @prashantgnet which version of diego are you using ?

**Comment by prashantgnet** [comment] 2018-03-07 06:48
cf-deployment version is 1.15.0 and following are releases details
```
Name                   Version 
binary-buildpack       1.0.16* 
capi                   1.49.0* 
cf-mysql               36.10.0*
cf-networking          1.10.0* 
cf-smoke-tests         40*     
cf-syslog-drain        5.1*    
cflinuxfs2             1.187.0*
consul                 191*    
diego                  1.35.0* 
dotnet-core-buildpack  2.0.1*  
garden-runc            1.11.1* 
go-buildpack           1.8.18* 
java-buildpack         4.8*    
loggregator            101.6*  
nats                   22*     
nodejs-buildpack       1.6.16* 
php-buildpack          4.3.48* 
postgres               23*     
prometheus             21.1.1* 
python-buildpack       1.6.8*  
routing                0.172.0*
ruby-buildpack         1.7.11* 
staticfile-buildpack   1.4.21* 
statsd-injector        1.2.0*  
uaa                    55*     
```
also kindly attached logs files, I have attached 2 logs for diego-api as we have 2 instance. database is single instance.

Thanks,
Prashant

[logs.zip](https://github.com/cloudfoundry/cf-deployment/files/1788076/logs.zip)

**Comment by prashantgnet** [comment] 2018-03-07 07:10
attaching following log file which is taken when I got the mentioned issue. As i mentioned, I am facing this particular issue intermediately.

Thanks,
Prashant

[logs.zip](https://github.com/cloudfoundry/cf-deployment/files/1788122/logs.zip)

**Comment by prashantgnet** [comment] 2018-03-08 05:25
similar issue is raised under 
https://github.com/cloudfoundry/diego-release/issues/380

**Comment by prashantgnet** [comment] 2018-03-08 07:39
Seems issue is related to https://discuss.pivotal.io/hc/en-us/articles/115014376027-App-staging-errors-due-to-BBS-and-Auctioneer-Restarts 

if yes, then how to disble audit logging under cf-deployment?

Thanks,
Prashant

**Comment by prashantgnet** [comment] 2018-03-08 10:21
[cf-runtime2.scheduler.a8d9e362-99ec-4089-b4b7-9c04966d5a12-20180308-051520-943793196.zip](https://github.com/cloudfoundry/cf-deployment/files/1792693/cf-runtime2.scheduler.a8d9e362-99ec-4089-b4b7-9c04966d5a12-20180308-051520-943793196.zip)

I getting issues under scheduler instance as well, check attached logs file, rename it to .tgz
Mostly likely database related 
```
{"timestamp":"1520491826.049449682","source":"auctioneer","message":"auctioneer.locket-lock.failed-to-acquire-lock","log_level":2,"data":{"error":"rpc error: code = 6 desc = lock-collision","lock":{"key":"auctioneer","owner":"a8d9e362-99ec-4089-b4b7-9c04966d5a12","type":"lock","type_code":1},"session":"3","ttl_in_seconds":15}}
{"timestamp":"1520491826.049449682","source":"auctioneer","message":"auctioneer.locket-lock.failed-to-acquire-lock","log_level":2,"data":{"error":"rpc error: code = 6 desc = lock-collision","lock":{"key":"auctioneer","owner":"a8d9e362-99ec-4089-b4b7-9c04966d5a12","type":"lock","type_code":1},"session":"3","ttl_in_seconds":15}}
{"timestamp":"1520492450.234708786","source":"auctioneer","message":"auctioneer.started","log_level":1,"data":{}}
{"timestamp":"1520492450.234800339","source":"auctioneer","message":"auctioneer.exited-with-failure","log_level":2,"data":{"error":"Exit trace for group:\nlock exited with error: Exit trace for group:\nsql-lock exited with error: sql-lock: failed to start in time\nlock-maintainer exited with nil\n\nlock-held-metrics exited with nil\ndebug-server exited with nil\n"}}
```

**Comment by prashantgnet** [comment] 2018-03-09 09:14
Just to avoid any performance bottleneck, I have tried increasing the resources for CF instances but issue was not sorted out. Then I scale down the environment to single AZ (Openstack) and things looks comparatively better now.  It seems that multi-zone environment is not yet stable. 

I will keep a watch on single zone environment for mentioned issue and will update you.

Thanks,
Prashant

**Comment by prashantgnet** [comment] 2018-03-09 10:04
I am getting mentioned issue on single zone environment as well.

**Comment by prashantgnet** [comment] 2018-03-12 09:19
I have setup fresh single zone cf-deployment v1.17.0 environment under Openstack.  I will keep a watch for the mentioned issue which is not yet re-produce.

I saw issues under bbs logs for MySQL database. 

[cf-deployment-v1.17.0.zip](https://github.com/cloudfoundry/cf-deployment/files/1802106/cf-deployment-v1.17.0.zip)

**Comment by jvshahid** [comment] 2018-03-13 17:29
@prashantgnet looks like there are a lot of slow queries in the logs you attached in https://github.com/cloudfoundry/cf-deployment/issues/425#issuecomment-371040795. I see only a single mysql instance, not sure what you meant by multi-az. which component were you referring to exactly ?

we use the following opsfile to tune mysql in our benchmarks. Let us know if that improves the performance of the mysql cluster so we can close this issue. 

```yaml
---
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/cf_mysql/mysql/innodb_buffer_pool_size?
  value: 12_000_000_000
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/cf_mysql/mysql/innodb_buffer_pool_instances?
  value: 16
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/cf_mysql/mysql/innodb_flush_log_at_trx_commit?
  value: 2
- type: replace
  path: /instance_groups/name=database/jobs/name=mysql/properties/cf_mysql/mysql/binlog_enabled?
  value: false
```

**Comment by prashantgnet** [comment] 2018-03-13 17:40
I have setup cf-deployment environment under Openstack which is by default setup three availability zone environment but only one database instance of MySQL. There is ops file in case, I would like to use MySQL cluster. 

Thanks for sharing tuning parameters for MySQL. I will update it in my environment and let you know the feedback for the same.

I would also like to know where these parameters are documented? not only for MySQL but for other CF instances as well. Those are very important for production like environment. 

Thanks,
Prashant

**Comment by prashantgnet** [comment] 2018-03-15 10:27
Updated MySQL tuning parameters but still getting following error message under diego-api for bbs job
```
[mysql] 2018/03/15 10:23:10 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:10 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:10 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:11 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:11 connection.go:96: invalid connection
[mysql] 2018/03/15 10:23:11 connection.go:96: invalid connection
[mysql] 2018/03/15 10:23:11 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:11 connection.go:96: invalid connection
[mysql] 2018/03/15 10:23:11 connection.go:96: invalid connection
[mysql] 2018/03/15 10:23:11 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:11 packets.go:36: unexpected EOF
[mysql] 2018/03/15 10:23:19 packets.go:36: unexpected EOF
panic: invalid connection

goroutine 1 [running]:
code.cloudfoundry.org/lager.(*logger).Fatal(0xc420234000, 0xb7fd80, 0x15, 0xbf1fc0, 0xc4201de120, 0x0, 0x0, 0x0)
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/lager/logger.go:154 +0x504
main.main()
        /var/vcap/packages/bbs/src/code.cloudfoundry.org/bbs/cmd/bbs/main.go:143 +0x3c95
2018/03/15 10:25:28 http: multiple response.WriteHeader calls
```

**Comment by goonzoid** [comment] 2018-03-15 21:29
> I would also like to know where these parameters are documented? not only for MySQL but for other CF instances as well. Those are very important for production like environment.

Agreed. We plan to do an investigation soon so that we can provide better guidelines around this specific case in our documentation. You can track that work here: https://www.pivotaltracker.com/story/show/155949688.

**Comment by goonzoid** [comment] 2018-03-15 21:41
@prashantgnet there's another config change that you could try, though please note that this isn't something we've been able to verify because we've not been able to reproduce this issue locally.

If you set `diego.bbs.sql.max_idle_connections` to `0` in your deployment manifest (or create an ops file to do the same), do you still see these errors in the bbs logs?

**Comment by prashantgnet** [comment] 2018-03-16 09:34
Deployed cf-deployment v1.19.0 and applied the changes suggested in https://github.com/cloudfoundry/cf-deployment/issues/425#issuecomment-372750495 comments for MySQL database. environment looks stable now and under review. 

For MySQL, we may configure additional parameter mentioned under http://bosh.io/jobs/mysql?source=github.com/cloudfoundry/cf-mysql-release&version=36.11.0 link 

max_idle_connections is not mentioned for CF MySQL release.  thanks for opening separate story fine tuning MySQL parameters. 

I will keep a watch for mentioned issue (bbs) for a week and if everything looks stable then we will close this issue.

Thanks,
Prashant

**Comment by jvshahid** [comment] 2018-03-16 15:35
I don't agree with setting `diego.bbs.sql.max_idle_connections` to `0`. This will affect the performance of BBS as it creates a new connection per query. Of course, this depends on the load in that environment, but I don't think that should be something that we recommend. The problem that @prashantgnet is experiencing is due to the constant loss of connectivity to the mysql database. I would like to understand the behavior of the Diego components better when those failures occur. That should be the focus of this github issue. 

Furthermore, I believe those EOFs are happening because the proxy is somehow marking the backend as failed. This could be due to the mysql server being slow or could be a symptom of another problem. @prashantgnet can you open a github issue in https://github.com/cloudfoundry/cf-mysql-release to address the mysql issues you are running into

**Comment by goonzoid** [comment] 2018-03-16 15:42
Sorry, should have put more detail with our previous comment. The intention was to see if setting `max_idle_connections` to `0` resolved the symptoms of the issue, in the hope that this information would help us to understand more about what might be causing the problems. I agree that I don't think this should be considered a "fix" and that setting it long term is not the best solution.

**Comment by prashantgnet** [comment] 2018-03-19 10:16
I have opened https://github.com/cloudfoundry/cf-mysql-release/issues/203 against MySQL release, fyi.
Thanks.

**Comment by goonzoid** [comment] 2018-03-19 18:19
@prashantgnet thanks. We'll close this now since you've opened the issue with the mysql team. We weren't able to find any other issues in the logs you provided.

**Closed by goonzoid** 2018-03-19 18:19 UTC
Labels: in progress
