### ISSUE TITLE
uaa should be downgrade from 55 to 54.

### ISSUE THREAD

**Issue by kukgini** [cloudfoundry/cf-deployment#224] opened 2017-08-31 10:57 UTC
Until fixed uaa-release issue: cloudfoundry/uaa-release#67 post-start scripts failed. Failed Jobs: uaa

**Comment by kukgini** [comment] 2017-09-01 01:41
I'm sorry to boder you. my problem is not the same kind of that issue. deployment failed because of config file corruption. I don't know why that things happen. but recreate vm was fixed post-start script problem. Actually version 45 works well to me now. 

Anyway, I'm not sure that issue still happen some other environments. if you sure that above issue is not comes from a uaa bug, please close this issue.

**Comment by dsabeti** [comment] 2017-09-02 00:00
Hi @kukgini, I'm not sure what went wrong with your environment, but it sounds like the problem isn't happening for you anymore and that it's not likely to be related to the Github issue on the UAA repo that you mentioned.

As such, I'll close this issue, but if you see the problem again, please re-open this and we'll try to help.

**Closed by dsabeti** 2017-09-02 00:00 UTC
Labels: unscheduled
